source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'INOMessageTextBox_Example', :exclusive => true do
  pod "INOMessageTextBox", :path => "../"
end

target 'INOMessageTextBox_Tests', :exclusive => true do
  pod "INOMessageTextBox", :path => "../"

  
end
